Bug 2111537: (image info): Introduce show-multiarch flag
openshift/oc pull request #1217
Opened 2022-08-05 13:44 UTC by ardaguclu

Currently if the passed image is multiarch image, we are throwing error
to force user to use `--filter-by-os` flag with the listed images in
that error.

This PR introduces new `show-multiarch` flag. `oc image info --show-multiarch`
command will continue working exactly the same way with now for single arch images.
However, this command(with new flag) will also show informations of platform specific images
embedded in multiarch image.

This flag supports json and default printing.

2022-08-05 13:48 UTC, ardaguclu commented
/uncc @deads2k @mfojtik

2022-08-06 11:59 UTC, ardaguclu commented
/retest

2022-08-08 07:14 UTC, ardaguclu commented
/cc @soltysh @deejross @ingvagabund could you please take a look at this new flag?. Thanks.

2022-08-08 07:17 UTC, ardaguclu commented
/cc @soltysh @deejross @ingvagabund

2022-08-08 14:59 UTC, deejross commented
/lgtm

2022-08-08 15:15 UTC, ingvagabund requested changes

2022-08-08 15:15 UTC, ingvagabund commented on pkg/cli/image/info/info.go
> +			var image []*Image
s/image/images

2022-08-08 15:46 UTC, ardaguclu commented on pkg/cli/image/info/info.go
> +			var image []*Image
@ingvagabund thanks. Done.

2022-08-08 17:18 UTC, soltysh approved these changes
/lgtm
/approve

2022-08-08 20:56 UTC, merged