WIP: Remove version patching for mac arm64 archs
openshift/oc pull request #1233
Opened 2022-09-07 13:31 UTC by ardaguclu

2022-09-07 13:50 UTC, ardaguclu commented
/uncc @deads2k @mfojtik 
/cc @soltysh @ingvagabund

2022-09-07 14:12 UTC, soltysh requested changes
/hold
we can't remove that functionality, at most I'm inclined to accept a warning which will explain users how to deal with these extracted binaries on mac

2022-09-07 14:28 UTC, closed without merging

2022-09-07 14:54 UTC, cfergeau commented
> /hold we can't remove that functionality, at most I'm inclined to accept a warning which will explain users how to deal with these extracted binaries on mac

Where would that warning be?
The problem is that https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.11.1/openshift-client-mac-arm64-4.11.1.tar.gz has non-working binaries because the version patching invalidated the binary checksum contained in the M1 binaries.
The right way of fixing this is to readd a valid signature right after doing the binary patching, but this is not going to be possible short-term. In the mean time, having working binaries with wrong version information on https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.11.1/openshift-client-mac-arm64-4.11.1.tar.gz would be much better than something which crashes.

2024-01-17 15:51 UTC, rgrunber commented
@cfergeau 

Hi, I was looking at https://mirror.openshift.com/pub/openshift-v4/aarch64/clients/ocp/4.14.7/ and noticed :

```
openshift-client-mac-arm64-4.14.7.tar.gz: FAILED
openshift-install-mac-arm64-4.14.7.tar.gz: FAILED
sha256sum: WARNING: 2 computed checksums did NOT match
```

when comparing against the listed `sha256sum.txt` file.

This started happening in the [4.11.11](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.11.11/) release folder ([4.11.10](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.11.10/) seemed valid). Is the mismatch related to this issue? I wasn't able to find documentation to indicate this was expected.

2024-01-17 16:14 UTC, cfergeau commented
I don't know how/when the sha256sum.txt file is generated, and when re-signing is triggered, but the timeframe and the binaries modified by the commit match: https://github.com/openshift/oc/commit/1fe58b72ebd785892d2144f220efec03e559751a

@ardaguclu any idea about this?

2024-01-23 09:26 UTC, ardaguclu commented
> @cfergeau
> 
> Hi, I was looking at https://mirror.openshift.com/pub/openshift-v4/aarch64/clients/ocp/4.14.7/ and noticed :
> 
> ```
> openshift-client-mac-arm64-4.14.7.tar.gz: FAILED
> openshift-install-mac-arm64-4.14.7.tar.gz: FAILED
> sha256sum: WARNING: 2 computed checksums did NOT match
> ```
> 
> when comparing against the listed `sha256sum.txt` file.
> 
> This started happening in the [4.11.11](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.11.11/) release folder ([4.11.10](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.11.10/) seemed valid). Is the mismatch related to this issue? I wasn't able to find documentation to indicate this was expected.

@rgrunber thanks for commenting. As far as I can see, this issue is related to the commit @cfergeau mentioned above. I'm investigating and working on it to fix.