Bug 2033167: oc extract: Create target directory if not exist
openshift/oc pull request #1248
Opened 2022-09-28 10:20 UTC by ardaguclu

Currently, `oc extract` command returns error, if target directory is not existed. This PR creates all nested directories prior to extract data.

This will easen usage of `oc extract` command.

2022-09-28 10:20 UTC, ardaguclu commented
/cc @deejross @ingvagabund

2022-09-28 10:25 UTC, ingvagabund commented on pkg/cli/extract/extract.go
> +	if o.TargetDirectory != "-" {
I'd prefer to move creation of the target directory as close to the line of code where it is needed. E.g. https://github.com/openshift/oc/blob/master/pkg/cli/extract/extract.go#L167

2022-09-28 10:38 UTC, ingvagabund commented on pkg/cli/extract/extract.go
> +	if o.TargetDirectory != "-" {
When creating the target directory right before it is needed one might get "permission denied". Knowing this in advance would help to save the entire extraction step on the other hand. Which makes the current change more preferable on the other hand.

2022-09-28 12:33 UTC, ardaguclu commented
e2e-agnostic-cmd failure is real
/hold

2022-09-28 14:50 UTC, soltysh requested changes

2022-09-29 08:06 UTC, ardaguclu commented
/test e2e-agnostic-cmd

2022-09-29 12:07 UTC, ardaguclu commented
None of the failures is related to this patch;

/retest-required
/hold cancel

2022-09-29 12:24 UTC, ingvagabund commented
/lgtm

2022-10-03 18:27 UTC, soltysh approved these changes
/approve

2022-10-04 07:09 UTC, ingvagabund commented
/retest-required

2022-10-04 11:52 UTC, ingvagabund commented
/retest-required

2022-10-04 15:26 UTC, merged