Bug 2000554: oc inspect: Also gather namespaces in which webhook services are running
openshift/oc pull request #1258
Opened 2022-10-06 10:27 UTC by ardaguclu

Currently, `oc inspect` obtains related objects by extracting them from `.status.relatedObjects` field in resources. However, `Validating|MutatingWebhookConfigurations` do not contain this field, instead they are storing services in `webhook.clientConfig.service` field. If services are in another namespace, `oc inspect` does not inspect those namespaces.

This PR adds ability to gather namespaces in which webhook services are running. That will shed more light on troubleshooting.

2022-10-06 10:46 UTC, ardaguclu commented on pkg/cli/admin/inspect/resource.go
> +			return nil
1 minute ago, I was preparing a new push to change this :). Thanks

2022-10-06 11:01 UTC, ingvagabund approved these changes

2022-10-06 11:02 UTC, ingvagabund commented
@kasturinarra would you please perform per-merge testing?

2022-10-07 08:51 UTC, soltysh requested changes
/lgtm cancel

2022-10-07 08:51 UTC, soltysh commented on pkg/cli/admin/inspect/resource.go
> +	if obj.GetKind() == "ValidatingWebhookConfiguration" || obj.GetKind() == "MutatingWebhookConfiguration" {
Nit: let's be explicit and move this after this block:https://github.com/openshift/oc/blob/0703a5baabaf66ca39604cfb655fd854d991b294/pkg/cli/admin/inspect/resource.go#L124-L127

This way we'll have clean `obtainReleatedObjects` and `obtainWebhookService` as two steps in `gatherRelatedObjects`. In the future, if someone decides to add `.status.relatedObject` to webhooks we'll still have this mechanism working.

2022-10-07 08:51 UTC, soltysh commented on pkg/cli/admin/inspect/resource.go
> +	if obj.GetKind() == "ValidatingWebhookConfiguration" || obj.GetKind() == "MutatingWebhookConfiguration" {
`obtainWebhookService` is a rename of your `obtainWebhookRelatedObjects`

2022-10-07 10:19 UTC, soltysh approved these changes
/lgtm
/approve

2022-10-07 10:26 UTC, ardaguclu commented
/hold

to see @kasturinarra's manual testing.

2022-10-07 11:50 UTC, kasturinarra commented
/cc qa-contact

2022-10-07 11:51 UTC, kasturinarra commented
/label cc-qa

2022-10-07 11:53 UTC, kasturinarra commented
/label cc-qa

2022-10-07 12:25 UTC, kasturinarra commented
/label qe-approved

2022-10-07 12:28 UTC, ardaguclu commented
/hold cancel

2022-10-07 16:18 UTC, merged