Clean up and modify to use library-go verify package
openshift/oc pull request #535
Opened 2020-08-26 19:50 UTC by jottofar

Modify to use proper k8s encoding/decoding and other minor clean up. Reference open comments from https://github.com/openshift/oc/pull/343. Use library-go verify package which was created since both CVO and the oc client use them.

2020-08-26 20:27 UTC, jottofar commented
/test unit

2020-08-31 14:11 UTC, jottofar commented
/retest

2020-09-09 18:01 UTC, jottofar commented
/retest

2020-09-09 19:37 UTC, damemi commented
/retest

2020-09-09 21:32 UTC, jottofar commented
/retest

2020-09-10 12:51 UTC, jottofar commented
/hold
for more testing

2020-09-10 12:55 UTC, jottofar commented
/test e2e-cmd

2020-09-10 13:22 UTC, damemi commented
@soltysh these failures look like infra, not related to these changes right?

2020-09-10 13:44 UTC, jottofar commented
@damemi @soltysh Thanks for looking. I thought they were infra and I've seen lots of former discussion on slack about them as well but nor recent, e.g. https://coreos.slack.com/archives/CEKNRGF25/p1586344512372800

2020-09-14 15:23 UTC, soltysh requested changes
Your bump seems incomplete, b/c it's missing `go.sum` being modified. Please re-run `go mod tidy` pointing library-go to master and it should pick all the necessary changes. It's also possible that the necessary library-go changes landed already during recent bumps.

2020-09-14 15:29 UTC, damemi commented
> It's also possible that the necessary library-go changes landed already during recent bumps.

@soltysh I think this is the case, because I was talking with @jottofar offline about this PR before we got the 1.19 bump in place. Wouldn't hurt to double-check though

2020-09-14 16:12 UTC, jottofar commented
Yeah, I picked up the changes to go.mod from @damemi:

$ git tattle go.mod
...
0384c91e3f (Maciej Szulik   2020-02-19 11:34:48 +0100  41)      github.com/mtrmac/gpgme v0.1.2 // indirect
e4de4fa9e9 (Maciej Szulik   2019-09-22 13:37:21 +0200  42)      github.com/opencontainers/go-digest v1.0.0-rc1
91ed2df2e0 (Mike Dame       2020-09-08 08:46:30 -0400  43)      github.com/openshift/api v0.0.0-20200901182017-7ac89ba6b971
91ed2df2e0 (Mike Dame       2020-09-08 08:46:30 -0400  44)      github.com/openshift/build-machinery-go v0.0.0-20200819073603-48aa266c95f7
91ed2df2e0 (Mike Dame       2020-09-08 08:46:30 -0400  45)      github.com/openshift/client-go v0.0.0-20200827190008-3062137373b5
91ed2df2e0 (Mike Dame       2020-09-08 08:46:30 -0400  46)      github.com/openshift/library-go v0.0.0-20200907120738-ea57b121ba1a
...
$ git log
commit 74a821379a4282914db8f36561babff3e02d83aa (HEAD -> ota-193, origin/ota-193)
Author: Jack Ottofaro <jottofar@redhat.com>
Date:   Wed Sep 9 11:45:07 2020 -0400

    Clean up and modify to use library-go verify package
    
    Modify to use proper k8s encoding/decoding and other minor cleanup.
    Reference open comments from #343.
    Use library-go verify package which was created since both CVO and
    the oc client use them.

commit b90dcf9705fd3edbea3dcbe3778fff6fcb01fc0a
Author: Jack Ottofaro <jottofar@redhat.com>
Date:   Wed Sep 9 11:42:16 2020 -0400

    Bump library-go to pick up new verify package
    
    Did:
    
    $ go mod tidy
    $ go mod vendor

commit 20df740e3f2811c5b0ad3e2741acd6af7cd9481e (upstream/master, origin/master, origin/HEAD, master)
Merge: 40679bed7 4e35f1e3d
Author: OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>
Date:   Wed Sep 9 09:18:47 2020 -0400

    Merge pull request #547 from damemi/oc-4.6-k8s-1.19-rebase
    
    Bug 1874056: Rebase k8s to 1.19.0

commit 40679bed7ca83644444df4994b7d5d73008b3725 (upstream/release-4.7, upstream/release-4.6)

2020-09-14 19:58 UTC, jottofar commented
/unhold

2020-09-15 10:57 UTC, soltysh commented
@jottofar still you're missing `go.sum` modifications, this file holds check sums for all the dependencies go.mod resolved.

2020-09-15 11:06 UTC, soltysh commented
Compare https://github.com/openshift/oc/pull/567, for example.

2020-09-15 13:44 UTC, jottofar commented
@soltysh gotcha. Believe I have it right now in commit [06d1694]( https://github.com/openshift/oc/pull/535/commits/06d169417d254ead11d8126ef1a268b66299c77a).

2020-09-15 14:06 UTC, soltysh approved these changes
/lgtm
/approve

2020-09-15 14:41 UTC, jottofar commented
/test build-rpms-from-tar

2020-09-15 21:10 UTC, jottofar commented
@soltysh https://github.com/openshift/oc/pull/567 merged so I had to rebase

2020-09-16 10:38 UTC, soltysh approved these changes
/lgtm

2020-09-16 14:48 UTC, merged