WIP: Oc 4.7 kubernetes 1.20.0 beta.2
openshift/oc pull request #648
Opened 2020-11-20 20:22 UTC by ingvagabund

TBD

2020-11-21 11:18 UTC, ingvagabund commented
/retest

2020-11-22 00:30 UTC, ingvagabund commented
/retest

2020-11-23 10:47 UTC, ingvagabund commented
https://github.com/openshift/origin/pull/25704 to address failing tests in `e2e-agnostic-cmd`.

2020-11-23 13:23 UTC, soltysh requested changes
As a follow-up have a look at how much of `oc debug` can we squash into `kubectl debug`

2020-11-23 13:23 UTC, soltysh commented on pkg/helpers/kubeconfig/loader.go
> -func NewPathOptionsWithConfig(configPath string) *kclientcmd.PathOptions {
I'm inclined to drop this file entirely. The only difference between this and `kclientcmd.NewDefaultPathOptions` is `LoadingRules.DoNotResolvePaths` but I'd try it, it shouldn't affect us.

2020-11-23 13:23 UTC, soltysh commented on pkg/helpers/kubeconfig/loader.go
> -func NewPathOptionsWithConfig(configPath string) *kclientcmd.PathOptions {
From what I see we use it in login, logout, project, request project and projects commands.

2020-11-24 14:42 UTC, ingvagabund commented
/retest

2020-11-24 15:39 UTC, soltysh approved these changes
/lgtm
/approve

2020-11-24 20:09 UTC, ingvagabund commented
/retest

2020-11-24 21:46 UTC, ingvagabund commented
/retest

2020-11-25 01:23 UTC, ingvagabund commented
/retest

2020-11-30 12:19 UTC, ingvagabund commented
/test e2e-aws

2020-11-30 14:52 UTC, soltysh approved these changes
/lgtm

2020-11-30 14:52 UTC, ingvagabund commented
/test e2e-aws

2020-12-02 12:05 UTC, ingvagabund commented
/hold

2020-12-02 15:59 UTC, soltysh commented
/close 
in favor of #660

2020-12-02 15:59 UTC, closed without merging