CCCMO cluster operator addition to must-gather
openshift/oc pull request #795
Opened 2021-03-30 13:29 UTC by Danil-Grigorev

`cloud-controller-manager` cluster operator should report healthy conditions on cluster startup, when collected in must-gather output.

2021-03-31 12:18 UTC, soltysh requested changes
/hold
this is not a default component of a 4.8 that I just checked, why would it be added here?

2021-04-16 13:37 UTC, Danil-Grigorev commented
@soltysh I'm trying to figure out how we could see `cloud-controller-manager` must-gather in default CI runs. Do you have any pointers if this PR is not the right way to go? cc @elmiko

2021-04-16 14:07 UTC, elmiko commented
+1 to what @Danil-Grigorev is saying. to add a little more context, we are building an operator for the out-of-tree providers and are getting into some heavy CI work. this operator won't be in the 4.8 payload, but we would still like to see it included in the must-gather, is there a way we can do this given the state of our development?

2021-04-20 14:34 UTC, soltysh commented
You could add an optional step in CI to inspect ccm.

2021-05-06 20:25 UTC, elmiko commented
@Danil-Grigorev i think we can close this one now?

2021-10-04 02:57 UTC, closed without merging