Download must-gather pod logs to get stdout info
openshift/oc pull request #846
Opened 2021-06-10 09:28 UTC by tssurya

Network-tools image leverages the must-gather tool
using the "--image" option. However some of the scripts
and tools used there just print the output to stdout.
It would be nice to get the must-gather pod logs as
well downloaded locally to see what happened while
the data was gathered or scripts were being run.

2021-06-10 13:22 UTC, tssurya commented
/bugzilla refresh

2021-06-10 15:50 UTC, soltysh requested changes
/hodl

2021-06-10 15:50 UTC, soltysh commented
/hold

2021-06-10 16:54 UTC, tssurya commented on pkg/cli/admin/mustgather/mustgather.go
> +			// copy the must-gather pod logs into the local destination dir
Thanks so much for having a look on short notice!

hmm ok I was told by Eric that there was plans to get this done. Must be some kind of miscommunication then! 

Aim was for both, to investigate if something fails and also for the stdout to get collected.

2021-06-10 16:56 UTC, soltysh commented on pkg/cli/admin/mustgather/mustgather.go
> +			// copy the must-gather pod logs into the local destination dir
must-gather container collection is possible, but shouldn't be bet on, I'd start with always gathering data into files.

2021-06-10 17:24 UTC, tssurya commented on pkg/cli/admin/mustgather/mustgather.go
> +			// copy the must-gather pod logs into the local destination dir
right I agree, but there is this slight other problem which is we are planning to use that image to run the scripts as a daemonset as well. So the image needs to be compatible with both must-gather and running as daemonset which is why this patch would be useful for us.

2021-06-11 10:41 UTC, soltysh commented on pkg/cli/admin/mustgather/mustgather.go
> +			// copy the must-gather pod logs into the local destination dir
I'd imagine a flag which would properly work for either of the two on the script side.

2021-11-11 09:35 UTC, closed without merging