Bug 1999891: Only collect backup data if must-gather collection fails
openshift/oc pull request #916
Opened 2021-09-01 02:22 UTC by MichaelWasher

Only collect backup data if must-gather collection fails, not if there are errors creating objects

2021-09-01 11:29 UTC, soltysh requested changes
Since you're trying to address a particular problem I'd prefer we focus on solving that rather than changing general approach which ensures we try to gather some data. How about just adding simple node validation logic?

2021-09-07 06:56 UTC, MichaelWasher commented
I have changed it to use node-name validation.

2021-09-08 11:12 UTC, soltysh requested changes
> I have changed it to use node-name validation.

Now you're causing all the test to flake due to problems validating node-name, we can't have validation that is stronger than API.

2021-09-09 02:51 UTC, MichaelWasher commented
> Now you're causing all the test to flake due to problems validating node-name, we can't have validation that is stronger than API.

Hi soltysh,

Sorry for the beginner questions that follow;

Can you please provide a little more insight into what you mean by this? Are you referring to the KubeAPI nodeName validations or another API?
----------------------
To explain why I chose this function is that (IIUC) the node-name validation inside the Kube-API uses this function to validate PodSpecs.
Aliasing: https://github.com/openshift/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L241-L245
Usage for PodSpecValidatePodTemplateSpec
 validation: https://github.com/openshift/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L3438-L3442
----------------------

Is there a repo I can review to view the prow/e2e* and other integration tests? Is there a process for running them locally against a test-cluster? 
I'm not familiar with the OpenShift CI/CD deployment and couldn't find any reference to the test-framework in this repo. This would save me from submitting failing PRs and consuming the Prow resources.

2021-09-17 03:52 UTC, MichaelWasher commented
/retest

2021-09-26 23:56 UTC, MichaelWasher commented
@soltysh 
Looking at the following pull request, I can see an update to the contributor list has caused these tests to fail too.
This is not excusing potential issues with my code but clearly there is an issue in the CI system.
https://github.com/openshift/oc/pull/930

Can you provide any further information about the flakiness of the CI system, any efforts being put into resolving this or direct me to another contributor that may be able to help?

2021-09-27 00:53 UTC, MichaelWasher commented
/retest-required

2021-10-06 14:26 UTC, soltysh requested changes

2021-10-06 14:26 UTC, soltysh commented
> Can you provide any further information about the flakiness of the CI system, any efforts being put into resolving this or direct me to another contributor that may be able to help?

Apologies for that, we've had issues with this particular tests while reworking it. At this point in time it should be all fixed. We're currently re-writing all of those test-cmd tests from bash to go tests, so it's disturbing at times :sweat:

2021-10-16 07:12 UTC, MichaelWasher commented on pkg/cli/admin/mustgather/mustgather.go
> +	if len(o.NodeName) != 0 {
I've resolved this with the most-recent commit.

2022-03-15 11:21 UTC, closed without merging